# Generated by Django 5.0.4 on 2024-04-12 17:38

import beats.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=21, verbose_name="name")),
                (
                    "file",
                    models.FileField(
                        upload_to="songs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav"]
                            )
                        ],
                        verbose_name="audio",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="covers/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg"]
                            ),
                            beats.validators.validate_cover,
                        ],
                        verbose_name="cover",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "bpm",
                    models.PositiveSmallIntegerField(default=0, verbose_name="BPM"),
                ),
                (
                    "key",
                    models.CharField(
                        default=None, max_length=6, verbose_name="Тональность"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Хэштеги",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Инструментал на продаже"
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Цена")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
            ],
        ),
    ]
