GENRE_CHOICES = [
    ('Afro', 'Afro'),
    ('Afrobeat', 'Afro beat'),
    ('Afropop', 'Afro pop'),
    ('Alternative', 'Alternative'),
    ('Alternativehiphop', 'Alternative hip hop'),
    ('Alternativerock', 'Alternative rock'),
    ('Alternativernb', 'Alternative rnb'),
    ('Ambient', 'Ambient'),
    ('Beats', 'Beats'),
    ('BoomBap', 'Boom Bap'),
    ('Break', 'Break'),
    ('Breakbeat', 'Break beat'),
    ('Chill', 'Chill'),
    ('Christian', 'Christian'),
    ('Classsoul', 'Class soul'),
    ('Classical', 'Classical'),
    ('Classicalrock', 'Classical rock'),
    ('Club', 'Club'),
    ('CloudRap', 'Cloud Rap'),
    ('ContemporaryRb', 'Contemporary Rb'),
    ('Country', 'Country'),
    ('Countryrock', 'Country rock'),
    ('Crunk', 'Crunk'),
    ('Dance', 'Dance'),
    ('Dancehall', 'Dance hall'),
    ('Dancernb', 'Dance rnb'),
    ('Dirtysouth', 'Dirty south'),
    ('Downtempo', 'Downtempo'),
    ('Drill', 'Drill'),
    ('Drumandbass', 'Drum and bass'),
    ('Dub', 'Dub'),
    ('Dubstep', 'Dubstep'),
    ('Eastcoast', 'East coast'),
    ('Edm', 'Edm'),
    ('Electronic', 'Electronic'),
    ('Electropop', 'Electro pop'),
    ('EmoHipHop', 'Emo Hip Hop'),
    ('ExperimentalHipHop', 'Experimental Hip Hop'),
    ('Folk', 'Folk'),
    ('FreestyleRap', 'Freestyle Rap'),
    ('Funk', 'Funk'),
    ('Gangsta', 'Gangsta'),
    ('GangstaRap', 'Gangsta Rap'),
    ('Grime', 'Grime'),
    ('HardcoreHipHop', 'Hardcore Hip Hop'),
    ('HipHop', 'Hip Hop'),
    ('HipHopSoul', 'Hip Hop Soul'),
    ('House', 'House'),
    ('Hyperpop', 'Hyperpop'),
    ('Indie', 'Indie'),
    ('Indierock', 'Indie rock'),
    ('Industrial', 'Industrial'),
    ('InstrumentalHipHop', 'Instrumental Hip Hop'),
    ('Jazz', 'Jazz'),
    ('JazzRap', 'Jazz Rap'),
    ('JerseyClub', 'Jersey Club'),
    ('K-pop', 'K-pop'),
    ('Latin', 'Latin'),
    ('Latinpop', 'Latin pop'),
    ('LatinTrap', 'Latin Trap'),
    ('LoFiHipHop', 'Lo Fi Hip Hop'),
    ('Lo-fi', 'Lo-fi'),
    ('Metal', 'Metal'),
    ('Neosoul', 'Neo soul'),
    ('Newsoul', 'New soul'),
    ('Oldschool', 'Old school'),
    ('Oldschoolhiphop', 'Old school hip hop'),
    ('Orchestral', 'Orchestral'),
    ('Pop', 'Pop'),
    ('Pop80s', 'Pop 80s'),
    ('Popcountry', 'Pop country'),
    ('Popelectronic', 'Pop electronic'),
    ('Pophiphop', 'Pop hip hop'),
    ('Poprnb', 'Pop rnb'),
    ('Poprock', 'Pop rock'),
    ('Poprap', 'Pop rap'),
    ('RageBeats', 'Rage Beats'),
    ('Rnb', 'Rnb'),
    ('Reggae', 'Reggae'),
    ('Reggaeton', 'Reggaeton'),
    ('Rock', 'Rock'),
    ('Roots', 'Roots'),
    ('Smoothrnb', 'Smooth rnb'),
    ('Soul', 'Soul'),
    ('SynthPop', 'Synth Pop'),
    ('Synthwave', 'Synthwave'),
    ('Techno', 'Techno'),
    ('Trashmetal', 'Trash metal'),
    ('Trance', 'Trance'),
    ('Trap', 'Trap'),
    ('Triphop', 'Trip hop'),
    ('Tropicalhouse', 'Tropical house'),
    ('Twostep', 'Two step'),
    ('UKgrime', 'UK grime'),
    ('Underground', 'Underground'),
    ('UndergroundHipHop', 'Underground Hip Hop'),
    ('Western', 'Western'),
    ('World', 'World')
]

KEY_CHOICES = [
    ('minor', (
        ('Abm', 'A-flat minor'),
        ('Am', 'A minor'),
        ('A#m', 'A-sharp minor'),
        ('Bbm', 'B-flat minor'),
        ('Bm', 'B minor'),
        ('Cm', 'C minor'),
        ('C#m', 'C-sharp minor'),
        ('Dbm', 'D-flat minor'),
        ('Dm', 'D minor'),
        ('D#m', 'D-sharp minor'),
        ('Ebm', 'E-flat minor'),
        ('Em', 'E minor'),
        ('Fm', 'F minor'),
        ('F#m', 'F-sharp minor'),
        ('Gbm', 'G-flat minor'),
        ('Gm', 'G minor'),
        ('G#m', 'G-sharp minor')
    )
     ),
    ('major', (
        ('Ab', 'A-flat major'),
        ('A', 'A major'),
        ('A#', 'A-sharp major'),
        ('Bb', 'B-flat major'),
        ('B', 'B major'),
        ('C', 'C major'),
        ('C#', 'C-sharp major'),
        ('Db', 'D-flat major'),
        ('D', 'D major'),
        ('D#', 'D-sharp major'),
        ('Eb', 'E-flat major'),
        ('E', 'E major'),
        ('F', 'F major'),
        ('F#', 'F-sharp major'),
        ('Gb', 'G-flat major'),
        ('G', 'G major'),
        ('G#', 'G-sharp major')
    )
     )
]
